### ISSUE TITLE
Icon from tabs is not the correct one

### ISSUE THREAD

**Issue by tonisfr** [shaqo-doon/shaqo_doon_frontend#9]
ENVIRONMENT: PROD
URL: https://shaqodoon.ro/
browser: Chrome

STEPS TO REPRODUCE:

 1. open URL in browser
 2. observe the icon from the tab

EXPECTED RESULTS:
icon should be the shaqodoon logo

ACTUAL RESULTS:
icon is the bot logo

**Comment by tonisfr** [comment]
![shaqo_doon_logo](https://user-images.githubusercontent.com/77154604/106900977-d7507500-66ff-11eb-9983-caf1fe32c7bb.png)

**Comment by tonisfr** [comment]
![bug2](https://user-images.githubusercontent.com/77154604/106924851-2e624400-6718-11eb-94b9-ae9bfddcb3ec.png)

**Comment by tonisfr** [comment]
![bug5](https://user-images.githubusercontent.com/77154604/106925653-f27bae80-6718-11eb-84fe-b922dfd07454.jpg)

**Comment by sergiuavram** [comment]
solved v0.25
fyi: the icon from the tab is called "favicon"

**Comment by tonisfr** [comment]
I knew that is called "favicon" but I forgot. Thanks for reminder.
retested on PROD environment
this issue has been fixed
closing the bug

**Comment by sebiboga** [comment]
favicon is now a more complex task and it is included in SEO tasks
thing is, while before favion was targeted only for website tab braowser, nowadays the favicon have multiple functions: see https://www.favicon-generator.org/

it will be tackle in a project called SEO later on
